# AI Ranking Configuration

# Weights for scoring calculation (must sum to 1.0)
ranking:
  weights:
    price_discount: 0.30          # Weight for discount vs market value
    location_score: 0.25          # Weight for location desirability
    property_condition: 0.15      # Weight for property condition
    legal_complexity: 0.15        # Weight for legal simplicity
    liquidity_potential: 0.15     # Weight for resale potential
  
  # Market value estimation parameters
  market_value:
    model_type: gradient_boosting  # Options: linear, gradient_boosting, neural_network
    features:
      - surface_sqm
      - rooms
      - bathrooms
      - floor
      - city_tier
      - distance_to_center
      - year_built
      - has_parking
      - has_elevator
      - energy_class
    
    # City tier pricing (avg EUR per sqm)
    city_tiers:
      tier_1:  # Major cities
        cities: [Roma, Milano, Firenze, Bologna, Venezia, Torino, Napoli]
        avg_price_sqm: 3500
        std_multiplier: 1.5
      tier_2:  # Regional capitals
        cities: [Genova, Palermo, Bari, Catania, Verona, Padova, Trieste]
        avg_price_sqm: 2200
        std_multiplier: 1.3
      tier_3:  # Other cities
        cities: []  # Default for unlisted
        avg_price_sqm: 1500
        std_multiplier: 1.2
  
  # Location scoring parameters
  location:
    poi_weights:
      metro_station: 0.25
      school: 0.15
      hospital: 0.15
      supermarket: 0.10
      park: 0.10
      restaurant: 0.10
      bank: 0.05
      pharmacy: 0.10
    
    max_distance_km:
      metro_station: 1.0
      school: 1.5
      hospital: 3.0
      supermarket: 1.0
      park: 2.0
      restaurant: 0.5
      bank: 2.0
      pharmacy: 1.0
  
  # Property condition scoring
  condition:
    keywords:
      excellent: [ottimo, ristrutturato, nuovo, recente, moderno]
      good: [buono, abitabile, discreto]
      fair: [da ristrutturare, necessita lavori, da ammodernare]
      poor: [pessimo, da demolire, rudere, collabente]
    
    scores:
      excellent: 100
      good: 75
      fair: 50
      poor: 25
      unknown: 60  # Default when not determined
  
  # Legal complexity scoring
  legal:
    complexity_factors:
      occupato: -30          # Property occupied
      pignoramento: -20      # Under seizure
      ipoteca: -15          # Has mortgage
      usufrutto: -10        # Has usufruct
      servitu: -5           # Has easements
      libero: 20            # Free and clear
      prima_asta: 10        # First auction
      seconda_asta: -5      # Second auction
      terza_asta: -10       # Third auction
  
  # Liquidity/resale potential
  liquidity:
    property_type_multipliers:
      Appartamento: 1.0
      Villa: 0.85
      Attico: 0.9
      Locale Commerciale: 0.7
      Ufficio: 0.75
      Magazzino: 0.6
      Terreno: 0.5
      Box: 0.8
      Rustico: 0.6
    
    size_preference:  # Optimal size ranges (sqm) for apartments
      min_optimal: 60
      max_optimal: 120
      penalty_per_sqm_outside: 0.5  # Score penalty per sqm outside range

# NLP Extraction Configuration
nlp:
  spacy_model: it_core_news_lg
  
  entity_patterns:
    price:
      patterns:
        - "(?:prezzo base|base d'asta|valore).*?€?\\s*([\\d.,]+)"
        - "(\\d{1,3}(?:[.,]\\d{3})*(?:[.,]\\d{2})?)"
      min_value: 1000
      max_value: 100000000
    
    surface:
      patterns:
        - "(\\d+)\\s*(?:mq|m2|metri quadri|metri quadrati)"
        - "superficie.*?(\\d+)"
      min_value: 10
      max_value: 10000
    
    rooms:
      patterns:
        - "(\\d+)\\s*(?:vani|locali|stanze|camere)"
        - "(?:bilocale|trilocale|quadrilocale)"
      mappings:
        monolocale: 1
        bilocale: 2
        trilocale: 3
        quadrilocale: 4
        cinque locali: 5
    
    property_type:
      keywords:
        Appartamento: [appartamento, alloggio, abitazione, casa, bilocale, trilocale]
        Villa: [villa, villetta]
        Attico: [attico, superattico, penthouse]
        Locale Commerciale: [negozio, locale commerciale, esercizio commerciale]
        Ufficio: [ufficio, studio]
        Magazzino: [magazzino, deposito, capannone]
        Box: [box, garage, posto auto, autorimessa]
        Terreno: [terreno, lotto, appezzamento]
        Rustico: [rustico, casale, cascina]
  
  city_extraction:
    use_ner: true  # Use spaCy NER for location extraction
    gazetteer_path: models/italian_cities.json
    
  date_extraction:
    patterns:
      - "(\\d{1,2})[/-](\\d{1,2})[/-](\\d{4})"
      - "(\\d{1,2})\\s+(?:gennaio|febbraio|marzo|aprile|maggio|giugno|luglio|agosto|settembre|ottobre|novembre|dicembre)\\s+(\\d{4})"
  
  court_extraction:
    patterns:
      - "Tribunale di ([A-Z][a-zà-ù]+)"
      - "Tribunale ([A-Z][a-zà-ù]+)"

# Vector Search Configuration
vector_search:
  collection_name: auctions
  dimension: 384  # For sentence-transformers model
  distance_metric: Cosine
  
  indexing:
    fields_to_embed:
      - title
      - description
      - full_text
    
    concatenation_template: "{title} {property_type} {city} {description}"
  
  search:
    top_k: 20
    score_threshold: 0.7
    rerank: true
    rerank_top_k: 10

# Scraper Configuration
scraper:
  targets:
    - name: pvp_giustizia
      url: https://pvp.giustizia.it/pvp/
      type: json_api
      endpoints:
        search: /it/ricerca
        detail: /it/dettaglio
      fallback_scraping: true
  
  rate_limiting:
    requests_per_minute: 30
    concurrent_requests: 2
    delay_between_requests_ms: 1000
    exponential_backoff: true
    max_retries: 3
  
  politeness:
    respect_robots_txt: true
    user_agent: "AI-RealEstate-Bot/1.0 (+https://yoursite.com/bot)"
    cache_responses: true
    cache_ttl_hours: 24
  
  parsing:
    timeout_seconds: 30
    max_page_size_mb: 10
    allowed_content_types:
      - text/html
      - application/json

# Notifications Configuration
notifications:
  enabled: true
  channels:
    email: true
    push: true
    websocket: true
  
  triggers:
    new_auction: true
    price_drop: true
    auction_ending_soon: true
    matching_preference: true
  
  throttling:
    max_per_user_per_hour: 10
    digest_mode: false
    digest_frequency_hours: 24

# Performance & Caching
performance:
  cache:
    enabled: true
    ttl_seconds:
      auction_list: 300
      auction_detail: 600
      search_results: 180
      market_stats: 3600
  
  pagination:
    default_page_size: 20
    max_page_size: 100
  
  database:
    pool_size: 10
    max_overflow: 20
    pool_timeout: 30
    pool_recycle: 3600

# Logging Configuration
logging:
  level: INFO
  format: json
  structured: true
  
  handlers:
    console:
      enabled: true
      level: INFO
    
    file:
      enabled: true
      level: DEBUG
      path: logs/app.log
      max_bytes: 10485760  # 10MB
      backup_count: 5
  
  loggers:
    scraper: DEBUG
    nlp: INFO
    api: INFO
    database: WARNING
